- include_tasks: debian.yml
  when:
    - ansible_lsb
    - (ansible_lsb.id, ansible_lsb.codename) in (('Debian', 'buster'), ('Debian', 'bullseye'), ('Debian', 'bookworm'), ('Raspbian', 'buster'), ('Ubuntu', 'bionic'), ('Ubuntu', 'focal'))

- include_tasks: oraclelinux.yml
  when:
    - ansible_distribution == "OracleLinux"
    - ansible_distribution_major_version == "8"
