- name: add fluentbit yum repository
  yum_repository:
    name: fluent-bit
    description: Fluent Bit
    file: fluent-bit
    gpgcakey: https://packages.fluentbit.io/fluentbit.key
    baseurl: https://packages.fluentbit.io/centos/$releasever/$basearch/
    gpgcheck: yes

- name: Install fluent-bit
  yum:
    name: "fluent-bit"
    state: "latest"
  notify: Restart Fluentbit
